### ISSUE TITLE
white name list

### ISSUE THREAD

**Issue by algobun** [universonic/shadowsocks-macos#1]
Do you have a plan support white name list ?

**Comment by universonic** [comment]
Sorry, I donnot have any plan for new features. This project is based on [ShadowsocksX-NG](https://github.com/universonic/ShadowsocksX-NG), and make sure everything works as desired (including some BUG fixes), and appended Japanese language pack. I recommend you to  submit an issue in original project. 

Something I can tell is that the Shadowsocks client uses [privoxy](https://www.privoxy.org/) for TCP/IP forwarding. Since the Shadowsocks client integrated this in program binary, you can just manually configure a customized rule file (also possible to use a whitelist) with it on your host.

I am going to close this issue, and please let me know if you have further questions.

**Comment by universonic** [comment]
Something I can tell is that the Shadowsocks client uses [privoxy](https://www.privoxy.org/) for TCP/IP forwarding. Since the Shadowsocks client integrated this in program binary, you can just configure it manually on your host.
