### ISSUE TITLE
Add new ciphers

### ISSUE THREAD

**Issue by wonsikin** [universonic/shadowsocks-macos#2]
Hey, guy, this is a good project.
Could you add new ciphers in this APP, such as `AEAD_CHACHA20_POLY1305`, `CHACHA20_IETF_POLY1305`

**Comment by universonic** [comment]
Hi, @wonsikin , thanks for demonstrating interest on this project. Unfortunately this project is intended to put emphasis on stability rather than functionality, so there is no plan to support any new features unless necessary. If you have further feature requirement, you can post an issue on original project: [shadowsocks/ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG).

Please let me know if you have further questions.

**Comment by wonsikin** [comment]
@universonic Thanks for your reply.
